services:
  nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/usr/share/nginx/html -d anagur.ru --email anastasia.gurianova.dev@mail.ru --agree-tos --non-interactive
    depends_on:
      - nginx

  certbot-renew:
    image: certbot/certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
    entrypoint: '/bin/sh -c ''echo "0 0 * * * certbot renew" | crontab - && crond -f'''
    depends_on:
      - nginx
