services:
  nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
    command: /bin/sh -c 'while :; do sleep 12h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/usr/share/nginx/html
      - ./certbot/data:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  certbot-renew:
    image: certbot/certbot
    volumes:
      - ./certbot/data:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot --webroot-path=/var/www/certbot; sleep 12h & wait $${!}; done'"
    depends_on:
      - nginx
